# Generated by Django 5.0.6 on 2024-05-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='description',
            new_name='descripcion',
        ),
    ]
